---

version: "3.8"
services:

  front-envoy:
    image: envoyproxy/envoy-dev:latest
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - ./access.log:/access.log
    networks:
      - envoymesh
    ports:
      - "8000:8000"
    command: ["-c", "/etc/envoy.yaml"]

  ext_authz-opa-service:
    image: openpolicyagent/opa:0.25.1-istio
    volumes:
      - ./policy.rego:/etc/policy.rego
    command:
      - run
      - --log-level=debug
      - --server
      - --log-format=json-pretty
      - --set=plugins.envoy_ext_authz_grpc.addr=:9002
      - --set=decision_logs.console=true
      - /etc/policy.rego
    networks:
      - envoymesh

  upstream-service:
    build:
      context: ./upstream
      dockerfile: service/Dockerfile
    networks:
      - envoymesh

networks:
  envoymesh: {}
