services:
  # Collector 2
  otel-collector-2:
    build:
      context: .
    restart: always
    command: ["--config=/etc/otelcol-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otelcol-config-from-file.yaml:/etc/otelcol-config.yaml
      - ./otelcol-output:/output
    depends_on:
      - prometheus

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-remote-write-receiver"

  grafana:
    container_name: grafana
    image: grafana/grafana:9.4.7
    restart: always
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_DEFAULT_THEME=${GF_USERS_DEFAULT_THEME}
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
