receivers:
  file:
    path: /output/data.txt

exporters:
  logging:

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

service:
  pipelines:
    metrics:
      receivers: [file]
      processors: []
      exporters: [logging, prometheusremotewrite]
