receivers:
  otlpjsonfile:
    include:
      - /output/data.json
    start_at:  beginning

exporters:
  logging:

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlpjsonfile]
      processors: [batch]
      exporters: [logging, prometheusremotewrite]
