receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

  file:
    path: /output/data.json

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, file]
