receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

  file:
    path: /output/data.txt

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]
