---

version: "3.8"
services:

  lua-envoy:
    image: envoyproxy/envoy-dev:latest
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    ports:
      - "8000:8000"
    command: ["-c", "/etc/envoy.yaml", "-l", "debug"]

  private-service:
    build:
      context: ./upstream
      dockerfile: service/Dockerfile
    networks:
      envoymesh:
        aliases:
          - private-service
          - upstream-service

networks:
  envoymesh: {}
