---

version: "3.8"

services:

  server:
    container_name: server
    image: golang:1.16.5
    working_dir: /go/src/server
    volumes:
      - ./server.go:/go/src/server/server.go
    command: ["go", "run", "server.go"]

  hey:
    container_name: hey
    image: bandwidth/hey
    build:
      context: github.com/rakyll/hey
    volumes:
      - ./image.bin:/tmp/image.bin
    command: ["-m", "PUT", "-D", "/tmp/image.bin", "-t", "0", "-n", "3", "-c", "3", "http://server:8080/"]
    depends_on:
      - server
